title: Your Name
description: Research | Data | Materials
url: "https://<username>.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default  # try: air, contrast, neon, dark

author:
  name: Tsung-Han Yang
  bio: Physicist | Data Scientist | Researcher
  location: USA
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://thyang-phys.github.io
