# Site Settings
title: "Tsung-Han Yang"  # Keeps the browser tab clean
masthead_title: "Research Portfolio <br> <span style='font-size:0.7em; font-weight:normal;'>AI for Science • Quantum Physicist • Materials Scientist</span>"
name: "Tsung-Han Yang, Ph.D."
description: "Postdoctoral Researcher at ORNL | AI for Science | Quantum Materials | Scattering, Modeling & Scientific Software"
url: "https://drthyang.github.io"
baseurl: ""

permalink: pretty

# Read CSS
custom_css:
  - /assets/css/custom.css

# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark 

# Technical Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Site Author Settings (This populates the sidebar)
author:
  name: "Tsung-Han Yang"
  avatar: "/assets/images/Tsung-Han_photo.png" 
  bio: "Postdoctoral Researcher @ ORNL <br> PhD in Physics @ Brown University"
  location: "Knoxville, TN"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:thyang.careers@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/drthyang"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=oMIW2moAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-0186-302X"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/thyang-profile"

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true # Keeps your bio visible on every post
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true # This fills the empty space on the left!

# Navigation Links (Top Header)
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/drthyang"
